# Indian equity market shock events, 2019-01 .. 2026-07
# Classification is relative to the 09:15 IST open of the listed session:
#   PRE_OPEN_OBSERVABLE = event public before 09:15 IST that day (avoidable at the open)
#   INTRADAY_SURPRISE   = broke during 09:15-15:30 IST (unavoidable at the open)
# Classifications were cross-checked against the actual NIFTY overnight GAP (open vs prior
# close): a large gap corroborates PRE_OPEN; a flat gap with a large close move corroborates
# INTRADAY. Where gap and narrative disagreed, confidence was lowered.
# nifty_move_pct is close-to-close. None = no single attributable session (do not fabricate one).
# READ the note field before using any row - several rows are explicit NEGATIVE findings.
MARKET_SHOCK_EVENTS = [
    dict(date='2019-02-26', description='Balakot airstrike on JeM camp ~03:30 IST; public before open', classification='PRE_OPEN_OBSERVABLE',
         confidence='high', nifty_move_pct=-0.41, note='Gap -0.96%. Small move - Nifty shrugged.'),
    dict(date='2019-05-20', description='Exit polls (Sun 19 May) projected large NDA win', classification='PRE_OPEN_OBSERVABLE',
         confidence='high', nifty_move_pct=3.69, note='Gap +2.15%.'),
    dict(date='2019-05-23', description='Lok Sabha counting day; gapped +1.4%, reversed to close red', classification='INTRADAY_SURPRISE',
         confidence='medium', nifty_move_pct=-0.69, note='AMBIGUOUS: outcome pre-open expected; reversal was sell-the-news.'),
    dict(date='2019-07-05', description='Union Budget FY20 (~11:00 IST): FPI surcharge shock', classification='INTRADAY_SURPRISE',
         confidence='high', nifty_move_pct=-1.14, note='Gap +0.15%; all damage post-speech. 2019-07-08 follow-through -2.14%.'),
    dict(date='2019-08-26', description='FPI surcharge rollback + stimulus, announced Fri 23 Aug post-close', classification='PRE_OPEN_OBSERVABLE',
         confidence='high', nifty_move_pct=2.11, note='Gap +1.58%.'),
    dict(date='2019-09-20', description='Surprise corporate tax cut to 22%, ~10:00-11:00 IST presser', classification='INTRADAY_SURPRISE',
         confidence='high', nifty_move_pct=5.32, note='Gap only +0.39%. Cleanest positive intraday event in sample.'),
    dict(date='2020-02-28', description='Global COVID contagion; worst global week since 2009', classification='PRE_OPEN_OBSERVABLE',
         confidence='high', nifty_move_pct=-3.71, note='Gap -2.16%.'),
    dict(date='2020-03-06', description='RBI Yes Bank moratorium effective 18:00 IST 5 Mar (post-close)', classification='PRE_OPEN_OBSERVABLE',
         confidence='high', nifty_move_pct=-2.48, note='Gap -2.90%. Confounded with global COVID selloff.'),
    dict(date='2020-03-09', description='Saudi-Russia oil price war (weekend OPEC+ collapse)', classification='PRE_OPEN_OBSERVABLE',
         confidence='high', nifty_move_pct=-4.9, note='Gap -2.25%.'),
    dict(date='2020-03-12', description='WHO pandemic declaration + Trump travel ban ~06:30 IST', classification='PRE_OPEN_OBSERVABLE',
         confidence='high', nifty_move_pct=-8.3, note='Gap -4.00%.'),
    dict(date='2020-03-13', description='Opened limit-down, 10% circuit ~09:20, 45-min halt, then reversed', classification='PRE_OPEN_OBSERVABLE',
         confidence='high', nifty_move_pct=3.81, note='WARNING: close +3.81% but OPEN gap -5.03%. Close-to-close mis-signs this day.'),
    dict(date='2020-03-16', description='Fed emergency 100bp cut to zero (Sun 15 Mar)', classification='PRE_OPEN_OBSERVABLE',
         confidence='high', nifty_move_pct=-7.61, note='Gap -3.69%.'),
    dict(date='2020-03-18', description='COVID capitulation; opened GREEN +1.35% then collapsed', classification='INTRADAY_SURPRISE',
         confidence='medium', nifty_move_pct=-5.56, note='No discrete pre-open catalyst; genuine intraday liquidation.'),
    dict(date='2020-03-23', description='Janata Curfew + weekend state lockdowns; worst NIFTY day ever', classification='PRE_OPEN_OBSERVABLE',
         confidence='high', nifty_move_pct=-12.98, note='Gap -9.14%, circuit hit ~09:58.'),
    dict(date='2020-03-25', description='Nationwide lockdown announced 20:00 IST on 24 Mar (post-close)', classification='PRE_OPEN_OBSERVABLE',
         confidence='high', nifty_move_pct=6.62, note='CAUTION: 24 Mar closed +2.51%; the reacting session RALLIED. Do not tag 24 Mar as a crash.'),
    dict(date='2020-03-30', description='Global recession repricing over weekend', classification='PRE_OPEN_OBSERVABLE',
         confidence='medium', nifty_move_pct=-4.38, note='Gap -3.17%. No discrete catalyst.'),
    dict(date='2020-05-04', description='Lockdown 3.0 extension (1 May holiday) + US-China tariff threats', classification='PRE_OPEN_OBSERVABLE',
         confidence='medium', nifty_move_pct=-5.74, note='Gap -3.31%. Two days of news into one open.'),
    dict(date='2021-02-01', description='Union Budget FY22 (~11:00 IST): big capex, no COVID tax', classification='INTRADAY_SURPRISE',
         confidence='high', nifty_move_pct=4.74, note='Gap +0.91%; rest earned during speech.'),
    dict(date='2021-02-26', description='US 10y yield spike (25 Feb US session) -> global unwind', classification='PRE_OPEN_OBSERVABLE',
         confidence='medium', nifty_move_pct=-3.76, note='Gap -1.38% vs -3.76% close; much was intraday continuation.'),
    dict(date='2021-04-12', description='COVID 2nd wave: record 1.69L cases + Maharashtra lockdown', classification='PRE_OPEN_OBSERVABLE',
         confidence='high', nifty_move_pct=-3.53, note='Gap -1.28%.'),
    dict(date='2021-11-26', description='Omicron VOC; SA announcement pre-open, WHO label post-close', classification='PRE_OPEN_OBSERVABLE',
         confidence='medium', nifty_move_pct=-2.91, note='Gap -1.13%. Partially ambiguous.'),
    dict(date='2022-01-24', description='Global Fed-tightening unwind; Nasdaq bear scare', classification='PRE_OPEN_OBSERVABLE',
         confidence='medium', nifty_move_pct=-2.66, note='Gap only -0.24%. Diffuse cause; low-value.'),
    dict(date='2022-02-24', description='Russia invades Ukraine; Putin address 08:00 IST (05:30 MSK)', classification='PRE_OPEN_OBSERVABLE',
         confidence='high', nifty_move_pct=-4.78, note='Gap -3.01%. Pre-open KNOWN but intraday ESCALATING.'),
    dict(date='2022-05-04', description='RBI off-cycle MPC: surprise 40bp repo + 50bp CRR, ~14:00 IST', classification='INTRADAY_SURPRISE',
         confidence='high', nifty_move_pct=-2.29, note='BEST intraday event. Opened +0.16% green; all damage post-14:00.'),
    dict(date='2022-05-19', description='Global stagflation rout after 18 May US session', classification='PRE_OPEN_OBSERVABLE',
         confidence='high', nifty_move_pct=-2.65, note='Gap -1.99%.'),
    dict(date='2022-06-13', description='US May CPI 8.6% (10 Jun 18:00 IST, post-close) -> 75bp repricing', classification='PRE_OPEN_OBSERVABLE',
         confidence='high', nifty_move_pct=-2.64, note='Gap -2.00%.'),
    dict(date='2023-01-25', description='Hindenburg Adani report, published 24 Jan US hours (post-close IST)', classification='PRE_OPEN_OBSERVABLE',
         confidence='medium', nifty_move_pct=-1.25, note='Timing INFERRED: 24 Jan closed exactly flat, 25 Jan -1.25%. Exact clock time unverified. Index impact modest; damage was in Adani names.'),
    dict(date='2023-03-13', description='SVB failure (10 Mar) + Signature closure (12 Mar, Sun)', classification='PRE_OPEN_OBSERVABLE',
         confidence='high', nifty_move_pct=-1.49, note='Gap +0.05%. NOT shock-grade - worst day of whole episode. Consider excluding.'),
    dict(date='2023-10-09', description='Hamas attack on Israel (Sat 7 Oct); first session after', classification='PRE_OPEN_OBSERVABLE',
         confidence='high', nifty_move_pct=-0.72, note='NON-EVENT for NIFTY. Useful as a control case.'),
    dict(date='2024-01-17', description='HDFC Bank Q3 miss (16 Jan post-close); stock -8%', classification='PRE_OPEN_OBSERVABLE',
         confidence='medium', nifty_move_pct=-2.09, note='Gap -1.75%. Earnings-driven, not geopolitical.'),
    dict(date='2024-06-03', description='Exit polls (Sat 1 Jun) projected landslide; biggest rally in 3y', classification='PRE_OPEN_OBSERVABLE',
         confidence='high', nifty_move_pct=3.25, note='Gap +3.58% - ENTIRE move in the opening print, faded slightly intraday.'),
    dict(date='2024-06-04', description='Lok Sabha counting: BJP ~240 vs 400+ projected; worst day since 2020', classification='INTRADAY_SURPRISE',
         confidence='high', nifty_move_pct=-5.93, note='Gap only -0.36%, close -5.93%. Best intraday surprise in dataset.'),
    dict(date='2024-08-05', description='Yen carry unwind; Nikkei -12.4% during 08:30-11:30 IST', classification='PRE_OPEN_OBSERVABLE',
         confidence='medium', nifty_move_pct=-2.68, note='AMBIGUOUS: cause (BoJ, payrolls) pre-open, gap -1.68%; Nikkei collapse ran live in Indian session.'),
    dict(date='2024-10-03', description='Iran 180-missile barrage (1 Oct) + SEBI F&O curbs (1 Oct); 2 Oct holiday', classification='PRE_OPEN_OBSERVABLE',
         confidence='high', nifty_move_pct=-2.12, note='Gap -1.33%. SEBI curbs separately material to options strategies.'),
    dict(date='2025-02-28', description='Trade-tension selloff, FII outflows; end of 5-month losing streak', classification='PRE_OPEN_OBSERVABLE',
         confidence='low', nifty_move_pct=-1.86, note='Diffuse cause, gap -0.50%. Consider excluding.'),
    dict(date='2025-04-07', description="Global rout after 2 Apr 'Liberation Day' tariffs + China retaliation", classification='PRE_OPEN_OBSERVABLE',
         confidence='high', nifty_move_pct=-3.24, note='Gap -5.00%, WIDER than close - recovered ~1.8% intraday. India tariff 26%.'),
    dict(date='2025-04-15', description='Relief rally: 9 Apr 90-day pause + electronics exemptions', classification='PRE_OPEN_OBSERVABLE',
         confidence='high', nifty_move_pct=2.19, note='Gap +2.36%. 14 Apr was a holiday.'),
    dict(date='2025-04-23', description='Pahalgam attack 22 Apr ~14:45 IST, 26 killed', classification='PRE_OPEN_OBSERVABLE',
         confidence='medium', nifty_move_pct=-0.19, note='NEAR NON-EVENT at index level. VIX spiked, NIFTY did not. Weak event.'),
    dict(date='2025-05-09', description='Operation Sindoor (strikes ~01:05 IST 7 May); peak stress 9 May', classification='PRE_OPEN_OBSERVABLE',
         confidence='medium', nifty_move_pct=-1.1, note='SMALL. Worst session of conflict only -1.10%. Range 2025-05-07..09.'),
    dict(date='2025-05-12', description='India-Pakistan ceasefire effective 17:00 IST Sat 10 May', classification='PRE_OPEN_OBSERVABLE',
         confidence='high', nifty_move_pct=3.82, note='Gap +1.72%. Relief rally ~3.5x larger than entire conflict drawdown.'),
    dict(date='2025-06-13', description='Israel strikes Iran (Operation Rising Lion); Brent +7%', classification='PRE_OPEN_OBSERVABLE',
         confidence='high', nifty_move_pct=-0.68, note='Gap -1.67%, recovered. 2025 Israel-Iran round NOT material for NIFTY.'),
    dict(date='2025-08-27', description='US 50% tariff on Indian goods took effect', classification='PRE_OPEN_OBSERVABLE',
         confidence='high', nifty_move_pct=None, note='NEGATIVE FINDING: no attributable session. Worst nearby day -1.02%. Do NOT insert a synthetic shock.'),
    dict(date='2026-02-01', description='Union Budget FY27 on a SUNDAY special session; STT on F&O hiked', classification='INTRADAY_SURPRISE',
         confidence='medium', nifty_move_pct=-2.33, note='WARNING: session MISSING from Yahoo ^NSEI. Verify vs NSE bhavcopy. STT hike changes per-trade costs from FY27.'),
    dict(date='2026-02-23', description='US Supreme Court struck down IEEPA tariffs (20 Feb); 50%->10%', classification='PRE_OPEN_OBSERVABLE',
         confidence='medium', nifty_move_pct=0.55, note='Structurally huge for India, near non-event in tape. Regime tag, not shock.'),
    dict(date='2026-03-02', description='US-Israel air war on Iran began Sat 28 Feb; Khamenei killed', classification='PRE_OPEN_OBSERVABLE',
         confidence='high', nifty_move_pct=-1.24, note='Gap -2.06%. Start of sustained ~10% March drawdown. Range 2026-03-02..30.'),
    dict(date='2026-03-19', description='Crude spike + hawkish Fed + record-low rupee + HDFCB chair exit', classification='PRE_OPEN_OBSERVABLE',
         confidence='medium', nifty_move_pct=-3.26, note='Gap -2.44%; HDFCB -8% at open confirms pre-open. Worst 2026 session.'),
    dict(date='2026-03-23', description='Weekend Iran escalation threats; Brent >$113; rupee ~94', classification='PRE_OPEN_OBSERVABLE',
         confidence='medium', nifty_move_pct=-2.6, note='Gap -1.26%; half the move intraday continuation.'),
    dict(date='2026-03-27', description='IRGC declared Strait of Hormuz closed to US/Israel-linked vessels', classification='INTRADAY_SURPRISE',
         confidence='low', nifty_move_pct=-2.09, note='UNVERIFIED CLASSIFICATION. Gap -0.57% vs -2.09% close suggests intraday, but announcement clock time could not be established. Exclude if classification-sensitive.'),
    dict(date='2026-04-08', description='US-Iran ceasefire agreed 7-8 Apr, announced outside Indian hours', classification='PRE_OPEN_OBSERVABLE',
         confidence='high', nifty_move_pct=3.78, note='Gap +3.16%. Largest positive shock of 2026.'),
    dict(date='2026-07-08', description='Ceasefire MOU collapse; fresh US strikes on Iran; Brent +5.7%', classification='PRE_OPEN_OBSERVABLE',
         confidence='medium', nifty_move_pct=-2.12, note='PARTIAL AMBIGUITY: gap only -0.57%, reports describe midday deterioration.'),
]
